version: '2'
services:
  # mysql
  db01:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  # web
  web01:
    build: ./docker
    image: docker:24
    ports:
      - "80:80"
    links:
      - "db01:db01"
    volumes:
      - ./public:/var/www/public_html
      - ./docker/logs:/var/log/httpd
      - ./docker/apache_conf/00_virtualhost.conf:/etc/httpd/conf.d/00_virtualhost.conf
